language: c

# TODO: ensure that a source distribution
# (made with stack sdist) also builds properly,
# not just that a "git clone" does.

git:
  depth: 5

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
  - $HOME/.local
  - $TRAVIS_BUILD_DIR/.stack-work

matrix:
  include:

  # Cabal
  - env: BUILD=cabal GHCVER=8.0.1 CABALVER=2.2 HAPPYVER=1.19.5 ALEXVER=3.1.7
    compiler: ": #GHC 8.0.1"
    addons: 
      {apt: {packages: [cabal-install-2.2,ghc-8.0.1,happy-1.19.5,alex-3.1.7], sources: [hvr-ghc]}}
  # Stack lts-7
  - env: BUILD=stack STACK_RESOLVER="lts-7"
    compiler: ": #stack"
    addons: 
      # ghc not used, but handy to ensure we have all deps
      {apt: {packages: [libgmp-dev,ghc-8.0.1], sources: [hvr-ghc]}}
#TO ADD: 
# - lts-6.35
# - lts-14.21

before_install:
  - |
    # Using compiler above sets CC to an invalid value, so unset it
    #set -x
    unset CC
    # stack prep
    mkdir -p "$HOME/.local/bin"
    export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$HOME/.cabal/bin:$PATH
    export LINUX64_STACK="https://github.com/commercialhaskell/stack/releases/download/v2.1.3/stack-2.1.3-linux-x86_64.tar.gz"
    travis_retry curl -L "${LINUX64_STACK}" | tar xz --wildcards --strip-components=1 -C $HOME/.local/bin '*/stack'

install:
  - |
    #set -x
    case "$BUILD" in
      cabal)
        ./.circleci/cabal-build.sh
      ;;
      stack)
        # build project with stack
        stack --version
        stack --resolver="$STACK_RESOLVER" ghc -- --version
        stack --resolver="$STACK_RESOLVER" setup
        stack build  --test --no-run-tests
      ;;
      *)
        echo unknown build tool!!
        exit 1
      ;;
    esac

script:
  - |
    case "$BUILD" in
      cabal)
        echo "You're still here? It's over. Go home."
      ;;
      stack)
        stack --resolver="${STACK_RESOLVER}" test --flag assumpta-core:test-doctests
      ;;
      *)
    esac

notifications:
  email: false
